### ISSUE TITLE
unbound always-nxdomain vs always-null?

### ISSUE THREAD

**Issue by Owyn** [ScriptTiger/Hosts-BL#1]
someone asked to implement always-null instead of always-nxdomain for unbound for the purpose of ad blocking (and it was done) https://github.com/NLnetLabs/unbound/issues/397 

so maybe that's better?

**Comment by ScriptTiger** [comment]
Thanks for bringing this up, @Owyn!

@spirillen, have you had a chance to do any testing with this? It seems like the performance was better with nxdomain in regards to multiple aspects, if I remember correctly, and that's what prompted us to switch from using null network to nxdomain in the first place, not just to reduce line count or file size.

The new `always-null` "shortcut" just condenses the line count to make implementing null networks faster, but I don't know if that alone would make it more performant than using `always-nxdomain`.

If anyone else has any additional input for this, please let us know. I think some performance testing and comparisons would be needed to really move forward with this.

Again, nice catch, @Owyn! I'll leave this issue open for now for more feedback.
