### ISSUE TITLE
Output file created with incorrect permissions

### ISSUE THREAD

**Issue by philipderrin** [ScriptTiger/Hosts-BL#3]
When running on Linux, the output file is created with owner write-only, global read-only permissions:

```
--w----r-- 1 philip philip 3473311 Jun 26 15:16 blocklist.conf
```

This is because the mode argument to `os.WriteFile` is `644` (`01204`). It should be `0644`.

**Comment by ScriptTiger** [comment]
Good catch, @philipderrin! I've just updated this repository, as well as a few others where I made the same mistake. I also published a new release to go with it. I definitely know better, so apologies again, and thanks for pointing that out! While I do use Linux for a great many things, I mostly develop for and on Windows and hadn't yet tested anything on Linux. Windows doesn't honor permissions in the same way, so I hadn't even noticed that. Thanks again!
