### ISSUE TITLE
[feature]: Have STDIN and STDOUT be the default input and output files respectively

### ISSUE THREAD

**Issue by T145** [ScriptTiger/Hosts-BL#4]
This way their regular files do not need to be specified.

**Comment by ScriptTiger** [comment]
Please try the latest release and let me know if that works.

You can either explicitly use `-i -` to specify using stdin and `-o -` to specify using stdout, or you can simply pipe input to stdin and it will automatically be detected and used as input by default. When stdin is used, stdout will be used by default.

**Comment by ScriptTiger** [comment]
I'm going to consider this issue closed. If you have any follow-up comments later, feel free to drop them here.
